insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Dragon Quest','Quando un’onda oscura si abbatte sulla città di Arba, i mostri che prima convivevano pacificamente con gli abitanti vengono travolti da una furia incontrollabile. Scegli tra il protagonista Lucyus o la protagonista Aurora e combatti al fianco di alcuni dei personaggi più amati della serie, come Alena, Bianca e Yangus, per calmare i mostri e riportare la pace nel regno.',26.12,1,15,'/img/home_dragon_quest.jpg','/img/carosello_dragon_quest.jpg','/img/carrello_dragon_quest.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('World of Final Fantasy','Con una grafica adorabile che conquisterà grandi e piccini, il gioco ti permette di raccogliere, allevare e far combattere mostri leggendari incolonnandoli l’uno sull’altro in vere e proprie torri di mostri. Ritrova i mostri più memorabili di FINAL FANTASY in questo mondo fantastico e colorato e vivi una storia epica insieme ai tuoi piccoli amici.',30.35,1,'/img/home_final_fantasy.jpg','/img/carosello_final_fantasy.jpg','/img/carrello_final_fantasy.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Odin Sphere','E'' un RPG d''azione in 2D a scorrimento orizzontale, ricco di mitologia nordica e l’atmosfera di un’opera wagneriana. La nuova versione è un remake completo in HD di quella classica originale per PS2 Odin Sphere di Vanillaware. Il regno di Valentine era il paese più potente del continente di Erion. La sua gente prosperava con il magico potere della Crystallization Cauldron, ma è stato distrutto in una notte fatale.',30.00,1,25,'/img/home_odin_sphere.jpg','/img/carosello_odin_sphere.jpg','/img/carrello_odin_sphere.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Valkyria Chronicles','Nel mondo alternativo di Valkyria Chronicles è l’anno 1935 e il continente Europeo è coinvolto in una guerra.',20.98,1,'/img/home_valkyria.jpg','/img/carosello_valkyria.jpg','/img/carrello_valkyria.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Gravity Rush','L''acclamato titolo per PS Vita arriva su PS4.',20.99,1,'/img/home_gravity_rush.jpg','/img/carosello_gravity_rush.jpg','/img/carrello_gravity_rush.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Resident Evil','Un operativo di primo livello scomparso. Una nave abbandonata. Quando gli agenti della BSSA indagano, scoprono una realtà terrificante che li porterà ai limiti della follia.',30.99,1,30,'/img/home_resident_evil.jpg','/img/carosello_resident_evil.jpg','/img/carrello_resident_evil.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Vampyr','Esplora le strade colpite dalla malattia in Vampyr – un Action /RPG dall’atmosfera cupa – sviluppato utilizzando l’Unreal Engine 4.',56.99,1,'/img/home_vampyr.jpg','/img/carosello_vampyr.jpg','/img/carrello_vampyr.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Wolfenstein 2','Wolfenstein II: The New Colossus è l''attesissimo seguito dell''acclamato sparatutto in soggettiva Wolfenstein: The New Order, sviluppato dal pluripremiato studio MachineGames',62.99,1,5,'/img/home_wolfenstein.jpg','/img/carosello_wolfenstein.jpg','/img/carrello_wolfenstein.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Far Cry 5','Far Cry 5 è un videogioco sparatutto in prima persona, sviluppato da Ubisoft Montreal, Ubisoft Reflections, Ubisoft Kiev, Ubisoft Shanghai e Ubisoft Toronto per PlayStation 4, Xbox One.',65.98,1,'/img/home_far_cry.jpg','/img/carosello_far_cry.jpg','/img/carrello_far_cry.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('God of War','Gioco PlayStation 4',30.99,1,18,'/img/home_god_of_war.jpg','/img/carosello_god_of_war.jpg','/img/carrello_god_of_war.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Uncharted','E'' un videogioco di avventura dinamica in terza-persona. I giocatori controllano Chloe Frazer, una cacciatrice di tesori abile e in grado di saltare, arrampicarsi, nuotare ed eseguire azioni acrobatiche. In combattimento, è possibile utilizzare armi da fuoco a lungo raggio, come fucili, e pistole a corto raggio come pistole e revolvers; sono disponibili anche esplosivi come granate e C4; vi è anche la possibilità di utilizzare armi e tattiche stealth per uccidere silenziosamente i nemici.',35.99,1,'/img/home_uncharted.jpg','/img/carosello_uncharted.jpg','/img/carrello_uncharted.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Uncharted','Nei panni della famosa cacciatrice di tesori Chloe Frazer dovrai collaborare con vecchi amici e nemici.',35.99,1,'/img/home_uncharted.jpg','/img/carosello_uncharted.jpg','/img/carrello_uncharted.jpg')


