insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Dragon Quest','I giocatori dovranno costruire una serie di strutture per soddisfare le stravaganti richieste di alcuni cittadini che non vedono l’ora di trovare una nuova casa.',26.12,1,15,'/img/home_dragon_quest.jpg','/img/carosello_dragon_quest.jpg','/img/carrello_dragon_quest.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('World of Final Fantasy','Con una grafica adorabile che conquisterà grandi e piccini, il gioco ti permette di raccogliere, allevare e far combattere mostri leggendari.',30.35,1,'/img/home_final_fantasy.jpg','/img/carosello_final_fantasy.jpg','/img/carrello_final_fantasy.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Odin Sphere','Odin Sphere Leifthrasir è un RPG d''azione in 2D a scorrimento orizzontale, ricco di mitologia nordica e l’atmosfera di un’opera wagneriana.',30.00,1,25,'/img/home_odin_sphere.jpg','/img/carosello_odin_sphere.jpg','/img/carrello_odin_sphere.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Valkyria Chronicles','Nel mondo alternativo di Valkyria Chronicles è l’anno 1935 e il continente Europeo è coinvolto in una guerra.',20.98,1,'/img/home_valkyria.jpg','/img/carosello_valkyria.jpg','/img/carrello_valkyria.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Gravity Rush','L''acclamato titolo per PS Vita arriva su PS4.',20.99,1,'/img/home_gravity_rush.jpg','/img/carosello_gravity_rush.jpg','/img/carrello_gravity_rush.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Resident Evil','Un operativo di primo livello scomparso. Una nave abbandonata. Quando gli agenti della BSSA indagano, scoprono una realtà terrificante che li porterà ai limiti della follia.',30.99,1,30,'/img/home_resident_evil.jpg','/img/carosello_resident_evil.jpg','/img/carrello_resident_evil.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Vampyr','Esplora le strade colpite dalla malattia in Vampyr – un Action /RPG dall’atmosfera cupa – sviluppato utilizzando l’Unreal Engine 4.',56.99,1,'/img/home_vampyr.jpg','/img/carosello_vampyr.jpg','/img/carrello_vampyr.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Wolfenstein 2','Wolfenstein II: The New Colossus è l''attesissimo seguito dell''acclamato sparatutto in soggettiva Wolfenstein: The New Order, sviluppato dal pluripremiato studio MachineGames.',62.99,1,5,'/img/home_wolfenstein.jpg','/img/carosello_wolfenstein.jpg','/img/carrello_wolfenstein.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Far Cry 5','Far Cry è tornato in America nel nuovo episodio della pluripremiata serie.',65.98,1,'/img/home_far_cry','/img/carosello_far_cry','/img/carrello_far_cry')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,Sconto,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('God of War','Gioco PlayStation 4',30.99,1,18,'/img/home_god_of_war.jpg','/img/carosello_god_of_war.jpg','/img/carrello_god_of_war.jpg')
insert into Prodotto(NomeProdotto,DescrizioneProdotto,Prezzo,Disponibile,LinkImmagine,LinkImmagineCarosello,LinkImmagineCarrello) values ('Uncharted','Nei panni della famosa cacciatrice di tesori Chloe Frazer dovrai collaborare con vecchi amici e nemici.',35.99,1,'/img/home_uncharted.jpg','/img/carosello_uncharted.jpg','/img/carrello_uncharted.jpg')


